package com.streamflix

import android.app.Application
import android.content.Context
import androidx.appcompat.app.AppCompatDelegate
import androidx.datastore.core.DataStore
import androidx.datastore.preferences.core.Preferences
import androidx.datastore.preferences.preferencesDataStore
import coil.ImageLoader
import coil.ImageLoaderFactory
import coil.disk.DiskCache
import coil.memory.MemoryCache
import coil.request.CachePolicy
import coil.util.DebugLogger
import com.streamflix.di.appModule
import com.streamflix.di.databaseModule
import com.streamflix.di.networkModule
import com.streamflix.di.repositoryModule
import com.streamflix.di.viewModelModule
import org.koin.android.ext.koin.androidContext
import org.koin.android.ext.koin.androidLogger
import org.koin.core.context.startKoin
import org.koin.core.logger.Level
import timber.log.Timber

/**
 * StreamFlix Application Class
 * 
 * Main application entry point that initializes:
 * - Dependency Injection (Koin)
 * - Timber logging
 * - Coil image loading
 * - Theme settings
 * 
 * @author StreamFlix Team
 * @version 1.0.0
 */
class StreamFlixApplication : Application(), ImageLoaderFactory {

    companion object {
        lateinit var instance: StreamFlixApplication
            private set
        
        // DataStore for app preferences
        val Context.dataStore: DataStore<Preferences> by preferencesDataStore(name = "streamflix_prefs")
    }

    override fun onCreate() {
        super.onCreate()
        instance = this

        // Initialize Timber for logging
        if (BuildConfig.DEBUG) {
            Timber.plant(Timber.DebugTree())
        }

        // Initialize Koin for Dependency Injection
        initializeKoin()

        // Initialize theme based on saved preference
        initializeTheme()

        Timber.d("StreamFlix Application initialized")
    }

    /**
     * Initialize Koin DI modules
     */
    private fun initializeKoin() {
        startKoin {
            androidLogger(Level.ERROR)
            androidContext(this@StreamFlixApplication)
            modules(
                listOf(
                    appModule,
                    networkModule,
                    databaseModule,
                    repositoryModule,
                    viewModelModule
                )
            )
        }
    }

    /**
     * Initialize app theme based on saved preferences
     */
    private fun initializeTheme() {
        // Default to system theme
        AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_FOLLOW_SYSTEM)
    }

    /**
     * Configure Coil ImageLoader with custom caching
     */
    override fun newImageLoader(): ImageLoader {
        return ImageLoader.Builder(this)
            .memoryCache {
                MemoryCache.Builder(this)
                    .maxSizePercent(0.25)
                    .build()
            }
            .diskCache {
                DiskCache.Builder()
                    .directory(cacheDir.resolve("image_cache"))
                    .maxSizeBytes(512L * 1024 * 1024) // 512MB
                    .build()
            }
            .memoryCachePolicy(CachePolicy.ENABLED)
            .diskCachePolicy(CachePolicy.ENABLED)
            .crossfade(true)
            .crossfade(300)
            .apply {
                if (BuildConfig.DEBUG) {
                    logger(DebugLogger())
                }
            }
            .build()
    }
}

/**
 * BuildConfig for the application
 * In a real project, this would be auto-generated by Gradle
 */
object BuildConfig {
    const val DEBUG = true
    const val APPLICATION_ID = "com.streamflix"
    const val BUILD_TYPE = "debug"
    const val VERSION_CODE = 1
    const val VERSION_NAME = "1.0.0-LiquidGlass"
}
